name: Called Workflow

on:
  workflow_call:
    inputs:
      fail:
        required: false
        default: false
        type: boolean
jobs:
  fail-or-not:
    name: called WF # fails depending on input, shortened to have a clearer wf visualization
    runs-on: ubuntu-latest
    steps:
      - name: One Step
        run: echo "About to make the decision...."
      - name: Decide
        if: ${{ inputs.fail }}
        run: echo "Must fail!"; exit 4711
