name: Caller Workflow

on:
  push:
    branches:
      - about_actions

# from https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#testing-out-your-action-in-a-workflow
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: actions/hello-world-composite-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash

  call_workflow:
    name: Call Local Workflow # workflows can be called like this:
    uses: ./.github/workflows/about_actions_called_workflow.yml
    #with:
    #  fail: true

    # invalid value workflow reference: workflows must be defined at the top level of the .github/workflows/ directory
    # uses: ./.github/workflows/about_actions/called_workflow.yml
  call_within_step:
    runs-on: ubuntu-latest
    steps:
      - name: Call From Step
        run: echo "can only call actions, not workflows from here!"

        # this fails:
        # uses: ./.github/workflows/about_actions_called_workflow.yml
        # Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under
        # '/home/runner/work/github-actions-pipeline-playground/github-actions-pipeline-playground/.github/workflows/about_actions_called_workflow.yml'.
        # Did you forget to run actions/checkout before running your local action?
