name: Caller Workflow

on:
  push:
    branches:
      - about_actions

jobs:
  build-backend:
    name: Call Local Workflow # workflows can be called like this:
    uses: ./.github/workflows/about_actions/called_workflow.yml
    #with:
    #  fail: true
