name: All Jobs and Steps May Fail

on:
  push:
    branches:
      - main
      - alpha
      - beta

jobs:
  build:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
     - name: run the script
       run: |
          echo Backend Build,
          echo with two lines.
  qa-test:
    name: QA Test
    runs-on: ubuntu-latest
    steps:
     - name: first failing step
       run: echo Hello, world!; exit 42
     - name: second step
       run: echo Hello, world!;
  integration-test:
    runs-on: ubuntu-latest
    name: Integration Test
    steps:
     - name: run the script
       run: echo Hello, world!
  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy Staging
    steps:
     - name: run the script
       run: echo Hello, world!
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy Production
    steps:
     - name: run the script
       run: echo Hello, world!
