
name: AlwaysContinue

on:
  push:
    branches:
      - main
jobs:
  go-on:
    name: always continue # fails depending on input, shortened to have a clearer wf visualization
    runs-on: ubuntu-latest
    steps:
      - name: Step One Step
        run: echo "About to make the decision...."
      - name: "Step Two: The failing test"
        id: thetest
        continue-on-error: true  # step succeeds
        run: |
          echo "some important message" > txt.log
          exit 42
      - name: Happy
        run: echo "I'm happily in between"
      - name: Print Log in any case
        run: cat txt.log
      - name: Print Log On Fail and Fail
        if: ${{ failure() }} # nothing happens, no failure here
        run: cat txt.log

  with-always:
    name: Using Always
    runs-on: ubuntu-latest
    steps:
      - name: Step One Step
        run: echo "About to make the decision...."
      - name: "Step Two: The failing test"
        id: thetest
        run: |
          echo "some important message" > txt.log
          exit 42
      - name: Print Log On Fail
        if: ${{ failure() }}
        run: |
          cat txt.log
          echo "Must not fail anymore!" #; exit 4711
      - name: Happy
        run: echo "I'm happily in between but will not run"
      - name: Print Log in any case
        if:  ${{ always() }}
        run: cat txt.log
